#!/bin/sh
set -eu
npm install
npx spago install
npm run build
url=`git remote -v | grep origin | awk '{ printf "%s", $2; exit }'`
cd dist
git init
git config user.name Bot
git config user.email "<>"
git commit -m _ --allow-empty
git remote add origin "$url"
git add -A
git commit --amend -q -m Autogenerated
git push -f origin master:gh-pages
