all: build

clean:
	rm -fr dist tools/output

build: dist/help.html node_modules tools/bower_components
	npm run build

dist/help.html: README.md
	mkdir -p $(@D)
	pandoc README.md -o $@

serve: node_modules
	npm run serve

doc: esdoc pursdoc

esdoc:
	esdoc

pursdoc:
	cd tools && pulp docs -- --format html

deploy: dist/.git/config all
	cd $(<D)/.. && \
	git add -A && \
	git commit --amend -q -m Autogenerated && \
	git push -f origin master:gh-pages

dist/.git/config:
	mkdir -p $(@D)
	url=`git remote -v | grep origin | awk '{ printf "%s", $$2; exit }'` && \
	cd $(@D)/.. && \
	git init && \
	git config user.name Bot && \
	git config user.email "<>" && \
	git commit -m _ --allow-empty && \
	git remote add origin "$$url"

node_modules: package.json
	npm install
	touch $@

tools/bower_components: tools/bower.json
	(cd tools && bower install)
	touch $@

.PHONY: doc deploy
