all: help.html build-tools

help.html: README.md
	pandoc README.md -o $@

build-tools:
	cd tools && $(MAKE) build

doc:
	esdoc

deploy: dist/.git/config all
	ln -f *.{css,html,js,png} $(<D)/..
	mkdir -p $(<D)/../tools
	ln -f tools/*.{css,html} tools/output/app.js $(<D)/../tools
	cd $(<D)/.. && \
	git add -A && \
	git commit --amend -q -m Autogenerated && \
	git push -f origin master:gh-pages

dist/.git/config:
	mkdir -p $(@D)
	url=`git remote -v | grep origin | awk '{ printf "%s", $$2; exit }'` && \
	cd $(@D)/.. && \
	git init && \
	git config user.name Bot && \
	git config user.email "<>" && \
	git commit -m _ --allow-empty && \
	git remote add origin "$$url"

.PHONY: doc deploy
