all: build build-tools

clean:
	rm -fr dist

build: dist/help.html node_modules
	node_modules/webpack/bin/webpack.js

dist/help.html: README.md
	mkdir $(@D)
	pandoc README.md -o $@

build-tools:
	cd tools && $(MAKE) build
	mkdir -p dist/tools
	ln -f tools/*.{css,html} tools/output/app.js dist/tools

serve: node_modules
	node_modules/webpack-dev-server/bin/webpack-dev-server.js

doc:
	esdoc

deploy: dist/.git/config all
	cd $(<D)/.. && \
	git add -A && \
	git commit --amend -q -m Autogenerated && \
	git push -f origin master:gh-pages

dist/.git/config:
	mkdir -p $(@D)
	url=`git remote -v | grep origin | awk '{ printf "%s", $$2; exit }'` && \
	cd $(@D)/.. && \
	git init && \
	git config user.name Bot && \
	git config user.email "<>" && \
	git commit -m _ --allow-empty && \
	git remote add origin "$$url"

node_modules:
	npm install

.PHONY: doc deploy
